#include "/Engine/Public/Platform.ush"

RWBuffer<float3> positions;
RWBuffer<float3> velocitys;

float deltaTime;
float3 pointer;


uint IDToIndex(uint3 id)
{
    return id.x + id.y * 4 + id.z * 4 * 4;
}


[numthreads(4, 4, 4)]
void BoidComputeShader(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= 4 || id.y >= 4 || id.z >= 4)
    {
        return;
    }
    positions[IDToIndex(id)] = (float3)id;
}
